### ISSUE TITLE
Implement Timeline Section for the Website

### ISSUE THREAD

**Issue by AryanK1511** [Seneca-Software-Developers-Club/seneca-innovators-website#16]
Create a visually engaging timeline section for the Seneca Innovators case competition. 

**Acceptance Criteria:**

- [x] The timeline section matches the design specifications in the provided Figma file.
- [x] Each milestone should include a date, brief description, and relevant visuals (e.g., icons or images) (Visuals are optional).
- [x] The timeline is fully responsive and functions correctly on both desktop and mobile screens.
- [x] Code is clean, reusable, and adheres to best practices, including accessibility standards.

**Additional Suggestions:**
-  Implement interactive elements, such as hover effects or animations, to enhance user engagement

Feel free to modify any sections to better suit your project's specific requirements!

**Comment by raghavdotdev** [comment]
![image](https://github.com/user-attachments/assets/2946ef5f-7b47-4dd0-8225-5507efaa11d2)
![image](https://github.com/user-attachments/assets/fba7dbcd-d240-465b-91d3-3562fa341e79)
